### ISSUE TITLE
Убери из репозитория файлы конфигов.

### ISSUE THREAD

**Issue by AnPogrebnyak** [MarharytaTsepiennikova/homework_3#1]
Ппка .idea и файлы *.iml не должны попадать в репозиторий.
Это настраивается при помощи файла .gitignore
https://ru.stackoverflow.com/questions/542088/%D0%9A%D0%B0%D0%BA-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%84%D0%B0%D0%B9%D0%BB-gitignore

**Comment by MarharytaTsepiennikova** [comment]
done!
